-- ============================================================
-- BLOOM RAFFLE · KazDentExpo Eurasia 2026
-- Supabase schema + Row Level Security
-- ============================================================
-- Run this in: Supabase Dashboard > SQL Editor
-- ============================================================

-- 1) TABLE
create table if not exists public.raffle_entries (
  id              uuid primary key default gen_random_uuid(),
  entry_number    bigint generated by default as identity unique,
  full_name       text not null,
  email           text not null unique,
  specialization  text not null,
  phone           text not null,
  clinic_name     text,
  country         text,
  created_at      timestamp with time zone default now()
);

-- Helpful indexes
create index if not exists idx_raffle_email
  on public.raffle_entries (lower(email));
create index if not exists idx_raffle_entry_number
  on public.raffle_entries (entry_number);
create index if not exists idx_raffle_created_at
  on public.raffle_entries (created_at desc);


-- 2) ROW LEVEL SECURITY
alter table public.raffle_entries enable row level security;

-- Drop old policies if re-running this script
drop policy if exists "Anonymous can insert raffle entries"      on public.raffle_entries;
drop policy if exists "Authenticated admins can read all"        on public.raffle_entries;
drop policy if exists "Authenticated admins can update entries"  on public.raffle_entries;
drop policy if exists "Authenticated admins can delete entries"  on public.raffle_entries;

-- Public (anon) can ONLY insert. They cannot read anyone else's entry.
create policy "Anonymous can insert raffle entries"
  on public.raffle_entries
  for insert
  to anon
  with check (true);

-- Authenticated admins can read everything
create policy "Authenticated admins can read all"
  on public.raffle_entries
  for select
  to authenticated
  using (true);

-- Authenticated admins can edit/delete (handy at the booth)
create policy "Authenticated admins can update entries"
  on public.raffle_entries
  for update
  to authenticated
  using (true)
  with check (true);

create policy "Authenticated admins can delete entries"
  on public.raffle_entries
  for delete
  to authenticated
  using (true);


-- 3) RPC: lookup raffle number by email (for re-shows on duplicate submit)
-- This bypasses RLS so anon callers can retrieve their own number after
-- accidentally re-submitting the same email.
create or replace function public.lookup_raffle_number_by_email(p_email text)
returns bigint
language sql
security definer
set search_path = public
as $$
  select entry_number
  from public.raffle_entries
  where lower(email) = lower(p_email)
  limit 1;
$$;

-- Allow anon to call the function
grant execute on function public.lookup_raffle_number_by_email(text) to anon;


-- ============================================================
-- 4) CREATE THE ADMIN USER
-- ============================================================
-- Do this in: Supabase Dashboard > Authentication > Users > Add user
--   - Type: "Create new user"
--   - Email: your admin email (e.g. info@bloomaligner.fr)
--   - Password: choose a strong password
--   - Auto Confirm User: YES
--
-- That's the email/password you'll use to sign into admin.html.
-- ============================================================


-- ============================================================
-- 5) (OPTIONAL) Quick sanity check — should return 0 right after setup
-- ============================================================
-- select count(*) from public.raffle_entries;
